config:
  LDAP_server:
    server: '127.0.0.1'
    port: 636
    user: VARyumin@sberned
    password: ******
    base_DN: DC=sberned,DC=lc

  DB_sever:
    server: '127.0.0.1'
    port: '5432'
    db_name: 'postgres'
    user: 'postgres'
    password: '******'
    tech_user:
      - postgres
      - sgr
      - css

  Mapping:

    read:
      group_bind: 'CN=read.prod.sgr,OU=PostgreSQL,OU=Linux Server,DC=company,DC=lc'
      grant:
        - SELECT
      default: True

    write:
      group_bind: 'CN=write.prod.sgr,OU=PostgreSQL,OU=Linux Server,DC=company,DC=lc'
      grant:
        - SELECT
        - INSERT
        - UPDATE
        - DELETE
